### ISSUE TITLE
Acceptance tests

### ISSUE THREAD

**Issue by mmun** [neon-bindings/neon-cli#10]
- [x] Add some acceptance tests (probably with mocha + chai + es2015 goodness). They should demonstrate that each command works by run them inside of a tmp folder and assert something about the files. The specs for https://github.com/SBoudrias/Inquirer.js should provide a good basis for dealing with user input.
- [x] Hook up CI (probably TravisCI)

**Comment by watilde** [comment]
Has this already resolved by #12? Great works :smiley:

**Comment by mmun** [comment]
Yes!
