### ISSUE TITLE
can we kill binding.cc?

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon-cli#18]
Both @eddyb and @mmun have brought up the fact that binding.cc is boring and an eyesore. Is it possible to implement it in pure Rust? How hard is it to implement what `NODE_MODULE` is doing?

**Comment by eddyb** [comment]
I think that `NODE_MODULE`'s implementation depends on the version of node.js.
If you want to go that route and hardcode what each version is doing, [this is the current state](https://github.com/nodejs/node/blob/master/src/node.h#L361-L456).
Probably the worst part would be emulating `__attribute__((constructor))`, which might involve injecting a static into an `.init` section or something similar.

**Comment by eddyb** [comment]
Also check out [the blame info](https://github.com/nodejs/node/blame/master/src/node.h#L361-L456) on that section of the file.
The only change this year was [replacing `Handle` with `Local`](https://github.com/nodejs/node/commit/4abc896a826c892c0d124989cc4ea6f490328942#diff-cad2dce043a459a0f31577b944fa9135R359) which seems like a breaking change anyway.

**Comment by dherman** [comment]
On IRC @eddyb just shared http://is.gd/fjAx3E :

``` rust
#[link_section = ".ctors"]
static CTORS: extern fn() = before_main;

extern fn before_main() {
    println!("hello from the other side");
}

fn main() {
    println!("hello");
}
```

We can define a Neon macro for this, and the macro could also abstract the `#[no_mangle]` attribute, although that still leads to a net increase in boilerplate in a project's .rs file, since they have to add a `macro_use` directive. Maybe that's acceptable though:

``` rust
#[macro_use]
extern crate neon;
// ...
neon!(node_main(mut module: Module) -> Result<()> {
    // ...
})
```

**Comment by dherman** [comment]
Actually once we go down this road there's a fair amount of boilerplate we can eliminate in that `node_main` declaration, including the type annotations:

```
neon!(node_main(module) {
    // ...
})
```

I think I'm learning to stop worrying and love the `#[macro_use]`.

**Comment by dherman** [comment]
Maybe that's a little overzealous, since you still may want the self-documenting nature of the type annotations. But anyway I think I could be convinced to go with a macro.
