### ISSUE TITLE
need acceptance test for hyphenated project name

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon-cli#19]
Was originally filed as rustbridge/neon#28. The functionality is there but it needs a test.

/cc @mmun @watilde

**Comment by dherman** [comment]
Example: `hello-world` becomes `hello-world` in NPM, `hello-world` in Cargo, but `hello_world` in the lib name.

**Comment by watilde** [comment]
I added a test for this on https://github.com/rustbridge/neon-cli/pull/20!
