### ISSUE TITLE
"npm install -g neon-cli" on ubuntu, error

### ISSUE THREAD

**Issue by ghost** [neon-bindings/neon-cli#25]
I did "neon new test" right after here's the error.
http://pastebin.com/quZQf2M3

**Comment by ghost** [comment]
I did removed "use strict"; I got some more errors.

**Comment by ghost** [comment]
"sudo npm install -g neon-cli@0.1.4" works

**Comment by watilde** [comment]
Could I ask you the version of Node.js/npm you used?

**Comment by ghost** [comment]
3.3.12

**Comment by ffflorian** [comment]
@x13machine
neon-cli uses ES6 features, such as `const`.

You need [at least Node 4.3.2](http://node.green/) to use ES6. You should consider using the [latest LTS](https://nodejs.org/en/download/).

**Comment by dherman** [comment]
Unfortunately we don't support Node 3. Sorry for the hassle!
