### ISSUE TITLE
neon new fails when git user name is undefined.

### ISSUE THREAD

**Issue by knpwrs** [neon-bindings/neon-cli#26]
See https://github.com/rustbridge/neon-cli/blob/be5e029f49d1144d3773a4a5e331bc19c888e24d/src/ops/neon_new.js#L29-L44

In the event that `config.user.name` is `undefined` (even when `config.user.email` _is_ defined) nothing is returned from `guessAuthor()`. I don't know if the `try/catch` was supposed to be an `else` for the `if` or if `gitconfig` actually can `throw` an error requiring both an `else` and a `catch`.

In other news, investigating this led me to discover that I don't have `user.name` in my gitconfig on this computer. Strange...

**Comment by watilde** [comment]
Hi! It seems really correct. Currently the method `guessAuthor()` return nothing when the `config.user.name` is undefined. the `guessAuthor` should always return an object which is assigned git config values.

I fixed this on #27.
