### ISSUE TITLE
optional ABI override in `neon build`

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon-cli#28]
Currently `neon build` automatically sets the Node ABI version number by extracting it from `process.versions.modules`. It should be possible to pass an optional ABI version like `neon build --abi=43` to support "cross-compiling" to different Node versions.

**Comment by shawedwa** [comment]
This makes it difficult to build Rust modules for Electron, since the ABI is typically different for Electron and one's own Node install.

**Comment by shawedwa** [comment]
It might be nice if it could pull the right version from the included node headers - NODE_MODULE_VERSION is defined in node_version.h.

PR: https://github.com/rustbridge/neon/pull/109

Edit: Will need to make a corresponding change to neon-cli to not pass in ABI version (unless explicitly overridden) .

**Comment by EdShaw** [comment]
And the corresponding change in neon-cli which actually resolves this issue:
https://github.com/rustbridge/neon-cli/pull/31

**Comment by dherman** [comment]
OK I'm closing this one, because as @EdShaw pointed out [it's not safe to compile to a different ABI than the headers you're compiling with](https://github.com/neon-bindings/neon/pull/123#issuecomment-257820188).
