### ISSUE TITLE
Prompted responses in `neon new` not escaped in generated package.json

### ISSUE THREAD

**Issue by bantic** [neon-bindings/neon-cli#30]
The response to the prompts in the `neon new` flow are not escaped when they are interpolated into the resulting `package.json`, which can lead to an invalid JSON structure. For instance, entering the value `my "cool" project` for the "description" prompt results in a package.json that looks like:

``` javascript
// ....
"description": "my "cool" project",
// ...
```

**Comment by dherman** [comment]
This issue was moved to neon-bindings/neon#238
