### ISSUE TITLE
test and troubleshoot Windows support

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon-cli#5]
Test and troubleshoot Windows support.

**Comment by photex** [comment]
ahoy!

I was going to take a shot at windows support. I also would like to sign into the slack team but wasn't able to. Is there a way to get invited?

**Comment by dherman** [comment]
@photex Would love your help! Sorry the slack wasn't quite working yet, I didn't get it set up right. You can get an invite automatically from [the Slackin app](http://rustbridge-community-slackin.herokuapp.com), which is now working, and then the new slack is up at http://rustbridge.slack.com. Hope to see you soon!

**Comment by watilde** [comment]
I tried this on the appveyor last night and got the following error message. I'll continue to figure out what's the problem.

```
  1) neon help should print neon usage:
     Uncaught Error: spawn C:\Program ENOENT
      at exports._errnoException (util.js:855:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
      at onErrorNT (internal/child_process.js:344:16)

  2) neon new should create a new project:
     Uncaught Error: spawn C:\Program ENOENT
      at exports._errnoException (util.js:855:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
      at onErrorNT (internal/child_process.js:344:16)
```

See also: https://ci.appveyor.com/project/watilde/neon-cli/build/10/job/ww6v1iphl4hqe4an

**Comment by dherman** [comment]
Doh, looks like problems with spaces in filenames. There's a bunch of hacky Python one-liners in the gypfile that are probably not safe for spaces in filenames, so that's one potential source of the bug.

**Comment by andruhon** [comment]
Is it ever worked on windows?

**Comment by dherman** [comment]
Windows is working and has CI via AppVeyor.
