### ISSUE TITLE
`neon build` force rebuilds everything after a compiler error

### ISSUE THREAD

**Issue by matklad** [neon-bindings/neon-cli#55]
Hi! I am writing an electron node addon based on https://github.com/dherman/neon-electron-hello (thank you very much for this example, I was able to get up in running in no time despite the fact that it was my first ever electron program).

The problem is, everytime I run `npm run build` when there is a compile time error in my Rust code, neon prints:

```
neon info forcing rebuild for new build settings
neon info running cargo
```

and then rebuilds the world, which is kinda slow:

```
   Compiling neon v0.1.15
   Compiling neon-build v0.1.15
   Compiling cslice v0.2.0
   Compiling gcc v0.3.45
   Compiling neon-hello v0.1.0 (file:///home/matklad/projects/neon-hello/native)
   Compiling neon-runtime v0.1.15
```

If I change my rust code without introducing any errors, then only my code gets rebuild. Perhaps this `forcing rebuild` is spurios? I didn't change `package.json`, so the build settings are the same. 

Or perhaps there's something wrong with my build setup?

I have `projects/neon-electron-hello` and `projects/neon-hello` and I've executed `npm link ../neon-hello` inside of `neon-electron-hello`.

**Comment by matklad** [comment]
So after erroneous compilation my artifacts.json looks like this:

`{"active":null,"targets":{}}`

**Comment by matklad** [comment]
These two lines are to blame: 

https://github.com/neon-bindings/neon-cli/blob/df442e3b5241ee29920203a13b4a33efeb080e6c/src/target.js#L77

https://github.com/neon-bindings/neon-cli/blob/df442e3b5241ee29920203a13b4a33efeb080e6c/src/target.js#L84

Perhaps we shouldn't remove artifacts if we were able to execute cargo regardless of exit code?

**Comment by jchlapinski** [comment]
+1 I have exactly the same problem, could someone from neon team comment on how can this be fixed? Regards

**Comment by dherman** [comment]
This issue was moved to neon-bindings/neon#242
