### ISSUE TITLE
Linker errors when running `cargo test` in native folder

### ISSUE THREAD

**Issue by jchlapinski** [neon-bindings/neon-cli#61]
I have prepared a repo with example that illustrates my problem: https://github.com/jchlapinski/neon-debug-example

Basically when I try to run unit tests for debug profile in my rust code (see https://github.com/jchlapinski/neon-debug-example/blob/master/neon-build-debug.sh) I get linker errors when compiling tests. Everything works OK, when I use release profile (see https://github.com/jchlapinski/neon-debug-example/blob/master/neon-build-release.sh).

Is this a neon-bindings bug or am I doing something wrong here?

Regards

**Comment by dherman** [comment]
This issue was moved to neon-bindings/neon#244
