### ISSUE TITLE
relicense to dual MIT/Apache-2.0

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon-cli#67]
I am planning to relicense this project under a dual MIT/Apache-2.0 license. In practice this won't limit what people can do with the codebase compared with today's single MIT license, but it's a better, more robust choice than MIT alone, and it will make it easier and cleaner to put neon and neon-cli together in a single repo (I'm pretty sure it wouldn't be _necessary_, but it'll be easier for people to understand).

# Contributor checkoff

To agree to relicensing, please leave a comment on this issue with:

```
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.
```

- [x] @dherman
- [x] @watilde
- [x] @mmun
- [x] @as-cii
- [x] @maxbrunsfeld
- [x] @GabrielCastro
- [x] @ffflorian
- [x] @jedireza
- [x] @linclark
- [x] @EdShaw
- [x] @bantic
- [x] @eddyb

I'll check people's names off as they leave their comments. Once we get all the signoffs I'll go ahead and do the relicensing.

I apologize for the inconvenience and _really_ appreciate everyone's help, both for this relicensing and for your contributions to Neon!

**Comment by dherman** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by eddyb** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by jedireza** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by mmun** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by as-cii** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by maxbrunsfeld** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by ffflorian** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by watilde** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

🐈

**Comment by GabrielCastro** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by EdShaw** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by bantic** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by linclark** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by dherman** [comment]
Thank you everyone!! 😍
